-- Run this in Supabase SQL Editor to enable attendance, notes, GPS ping, and visit reports.

create table if not exists public.daily_activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  entry_type text not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_daily_activity_logs_user_created
  on public.daily_activity_logs (user_id, created_at desc);

create index if not exists idx_daily_activity_logs_entry_created
  on public.daily_activity_logs (entry_type, created_at desc);

alter table public.daily_activity_logs enable row level security;

-- Users can read their own logs.
drop policy if exists "daily_logs_select_own" on public.daily_activity_logs;
create policy "daily_logs_select_own"
  on public.daily_activity_logs
  for select
  using (auth.uid() = user_id);

-- Users can insert their own logs.
drop policy if exists "daily_logs_insert_own" on public.daily_activity_logs;
create policy "daily_logs_insert_own"
  on public.daily_activity_logs
  for insert
  with check (auth.uid() = user_id);

-- Optional: allow users to update/delete only their rows if needed in future.
